### PR TITLE
Support Portainer Agents

### PR DESCRIPTION
**Pull request by ralphg6**
Based on [Inside a Swarm cluster](http://portainer.readthedocs.io/en/stable/deployment.html#inside-a-swarm-cluster)

### CODE REVIEW

**Comment by flaviostutz** [comment]
I checked out this PR to my machine but cannot merge because when I try to login Portainer shows me an error: "dial unix /var/run/docker.sock: connect: no such file or directory". Is it working on your machine (without the Traefik part)?

**Comment by ralphg6** [comment]
Did you delete the contents of the 'portainer' volume before re-executing? The portainer only starts the configuration if the '/ data' folder is empty. It ran normally here!

**Comment by ralphg6** [comment]
This reported error would happen if it were attempting to use the old configuration, since the volume '/var/run/docker.sock' has not mapped.

**Comment by flaviostutz** [comment]
Great! It worked after removing previous volume. Thanks.

**Pull request merged**
